### PR TITLE
Fabric 1.17

### PR DESCRIPTION
**Pull request by NikitaCartes**
It's not ready yet because of messed up with coordinates.

In yarn they was changes in such way:
```
minX -> maxZ
minY -> minX
minZ -> minY
maxX -> minZ
maxY -> maxX
maxZ -> maxY
```
As a result I have this
image
and this 
```
[22:38:15] [Worker-Main-9/ERROR] (Minecraft) Detected setBlock in a far chunk [15, 0], pos: BlockPos{x=240, y=2, z=9}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/structure_feature / bettermineshafts:bettermineshaft]
[22:38:15] [Worker-Main-9/ERROR] (Minecraft) Detected setBlock in a far chunk [15, 0], pos: BlockPos{x=240, y=2, z=9}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/structure_feature / bettermineshafts:bettermineshaft]
[22:38:15] [Worker-Main-10/ERROR] (Minecraft) Detected setBlock in a far chunk [15, 0], pos: BlockPos{x=240, y=2, z=9}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/structure_feature / bettermineshafts:bettermineshaft]
[22:38:16] [Worker-Main-9/ERROR] (Minecraft) Detected setBlock in a far chunk [15, 0], pos: BlockPos{x=240, y=2, z=9}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/structure_feature / bettermineshafts:bettermineshaft]
[22:38:18] [Worker-Main-8/ERROR] (Minecraft) Failed to fetch mob spawner entity at (240, 2, 0)
[22:38:26] [Server thread/ERROR] (Minecraft) Invalid bounding box data, inverted bounds for: BlockBox{minX=12, minY=434, minZ=439, maxX=12, maxY=439, maxZ=6}
[22:38:26] [Server thread/ERROR] (Minecraft) Invalid bounding box data, inverted bounds for: BlockBox{minX=5, minY=434, minZ=439, maxX=5, maxY=439, maxZ=-1}
[22:38:26] [Server thread/ERROR] (Minecraft) Invalid bounding box data, inverted bounds for: BlockBox{minX=216, minY=209, minZ=217, maxX=216, maxY=31, maxZ=211}
[22:38:26] [Server thread/ERROR] (Minecraft) Invalid bounding box data, inverted bounds for: BlockBox{minX=-22, minY=207, minZ=-18, maxX=-22, maxY=32, maxZ=28}
```

### CODE REVIEW

**Comment by NikitaCartes** [comment]
Now they properly generated on right height but they kind of small and rare (except spawn-chunk)
image
image

**Comment by NikitaCartes** [comment]
All things work normally without errors and warnings

**Comment by yungnickyoung** [comment]
Hey, very cool of you to do all this. I'll take a look at this soon :)

**Comment by yungnickyoung** [comment]
I'm confused, what are you doing to build this? Several dependencies aren't resolved, not to mention YUNG's API doesn't even exist for 1.17.

**Pull request merged**
